<?php
define("SLACK_OAUTH_URL",     $_ENV['SLACK_OAUTH_URL']);
define("SLACK_CLIENT_ID",     $_ENV['SLACK_CLIENT_ID']);
define("SLACK_CLIENT_SECRET", $_ENV['SLACK_CLIENT_SECRET']);
define("SLACK_COMMAND_TOKEN", $_ENV['SLACK_COMMAND_TOKEN']);
?>
